spring:
  datasource:
    username: admin
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://0.0.0.0:5432/mock_test
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
     show-sql: true
     hibernate:
       format-sql: true
